language: nix
nix: 2.3.6
env:
  - EMACS_VERSION=26.3
  - EMACS_VERSION=27.1
  - EMACS_VERSION=27.2
script: nix-build nix/emacs-${EMACS_VERSION}.nix
cache:
  directories:
  - $HOME/nix.store
before_install:
  - sudo mkdir -p /etc/nix
  - echo "substituters = https://cache.nixos.org/ file://$HOME/nix.store" | sudo tee -a /etc/nix/nix.conf > /dev/null
  - echo 'require-sigs = false' | sudo tee -a /etc/nix/nix.conf > /dev/null 
before_cache:
- mkdir -p $HOME/nix.store
- nix copy --to file://$HOME/nix.store -f nix/emacs-${EMACS_VERSION}.nix buildInputs
